services:
  pythonstatusserver:
    image: projectmakers/pythonstatusserver:latest
    container_name: pythonstatusserver
    ports:
      - "${STATUS_SERVER_PORT}:${STATUS_SERVER_PORT}"
    env_file:
      - /usr/local/bin/env/statusServer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - pm_network

networks:
  pm_network:
    external: true
    name: pm_network
