name: Push Docker Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # Schritt 2: Docker Buildx einrichten
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Schritt 3: Bei DockerHub einloggen
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Schritt 4: Docker-Image bauen und pushen zu DockerHub
      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pythonstatusserver:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pythonstatusserver:${{ github.sha }}
